apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: test-wordpress
type: Opaque
data:
  # La contraseña es: passmysqlk8s (en base64)
  mysql-root-password: cGFzc215c3Fsazhz
